# Generated by Django 5.2 on 2025-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_group_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='memo',
            name='group',
        ),
        migrations.AddField(
            model_name='memo',
            name='tags',
            field=models.ManyToManyField(related_name='memos', to='memo.tag'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
