# Generated by Django 5.2 on 2025-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_tag_remove_memo_group_memo_tags_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
